# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs_rst/conf.py

python:
  version: 3.7
  install:
    - requirements: docs_rst/requirements.txt
    - method: pip
      path: pivotpy
