source "https://rubygems.org"

gem 'github-pages', group: :jekyll_plugins

# Added at 2019-11-25 10:11:40 -0800 by jhoward:
gem "nokogiri", "< 1.13.5"
gem "jekyll", ">= 3.7"
gem "kramdown", ">= 1.17.0"
